### ISSUE TITLE
 "God mode" Windows Master Control Panel

### ISSUE THREAD

**Issue by MiChaelinzo** [mikeroyal/Windows-11-Guide#25]
1.) Make sure you system account has administrative privilages.
2.) Right-click on the Windows 10 desktop and choose New > Folder.
3.) Name the folder: GodMode.{ED7BA470-8E54-465E-825C-99712043E01C} and hit enter/return.

Here you go!
Ready to enter into yours!
🅦🅘🅝🅓🅞🅦🅢 🅜🅐🅢🅣🅔🅡 🅒🅞🅝🅣🅡🅞🅛 🅟🅐🅝🅔🅛

**Comment by Bennett-Fourr** [comment]
I made a pull request for this and one other thing. It's located at https://github.com/mikeroyal/Windows-11-Guide/pull/89
